paginate = 5
theme = "PaperMod"
enableEmoji = true
title = "airscript.it" 
enableRobotsTXT = true
pygmentsUseClasses = true
copyright = "airscript.it"
enableInlineShortcodes = true
defaultContentLanguage = "it"
baseURL = "https://blog.airscript.it"

[[headers]]
for = '/**'

[headers.values]
Content-Security-Policy = "script-src 'self'"
Referrer-Policy = "strict-origin-when-cross-origin"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Permissions-Policy = "accelerometer=(self), ambient-light-sensor=(self), autoplay=(self), battery=(self), camera=(self), cross-origin-isolated=(self), display-capture=(self), document-domain=(self), encrypted-media=(self), execution-while-not-rendered=(self), execution-while-out-of-viewport=(self), fullscreen=(self), geolocation=(self), gyroscope=(self), keyboard-map=(self), magnetometer=(self), microphone=(self), midi=(self), navigation-override=(self), payment=(self), picture-in-picture=(self), publickey-credentials-get=(self), screen-wake-lock=(self), sync-xhr=(self), usb=(self), web-share=(self), xr-spatial-tracking=(self), clipboard-read=(self), clipboard-write=(self), gamepad=(self), speaker-selection=(self), conversion-measurement=(self), focus-without-user-activation=(self), hid=(self), idle-detection=(self), interest-cohort=(self), serial=(self), sync-script=(self), trust-token-redemption=(self), window-placement=(self), vertical-scroll=(self)"

[languages.it]
weight = 1
languageName = "it"
languageAltTitle = "Italiano"
contentDir = "content/italian"

description = """
Ti do il benvenuto su airscript.it!
Su questo blog troverai articoli relativi ad informatica, motivazione e molto altro!
"""

[languages.it.homeInfoParams]
Title = "Oh, ciao! 👋🏻"

Content = """
Ti do il benvenuto su **airscript.it**!  
Su questo blog troverai articoli relativi ad informatica, motivazione e molto altro!  
Se vuoi, puoi supportarmi attraverso i link sotto o lasciando una 🌟 al [blog su GitHub](https://github.com/Airscripts/blog.airscript.it).  
&nbsp;  
Qui non si bada a spese!  
*John Hammond, Jurassic Park.*
"""

# [[languages.it.menu.main]]
# weight = 5
# name = "Archivio"
# url = "archives/"

[[languages.it.menu.main]]
weight = 10
name = "About"
url = "about/"
pageRef = "about"
identifier = "About"

[[languages.it.menu.main]]
weight = 15
name = "Cerca"
url = "search/"
pageRef = "search"
identifier = "Search"

[languages.en]
weight = 2
languageName = "en"
languageAltTitle = "English"
contentDir = "content/english"

description = """
I welcome you on airscript.it!
On this blog you'll find articles related to computer science, motivation and much more!
"""

# [[languages.en.menu.main]]
# weight = 5
# name = "Archive"
# url = "archives/"

[[languages.en.menu.main]]
weight = 10
name = "About"
url = "about/"
pageRef = "about"
identifier = "About"

[[languages.en.menu.main]]
weight = 15
name = "Search"
url = "search/"
pageRef = "search"
identifier = "Search"

[languages.en.homeInfoParams]
Title = "Oh, hello! 👋🏻"

Content = """
I welcome you on **airscript.it**!  
On this blog you'll find articles related to computer science, motivation and much more!  
If you want, you can support me through the link below or leaving a 🌟 at my [blog on GitHub](https://github.com/Airscripts/blog.airscript.it).  
&nbsp;  
Spared no expense!  
*John Hammond, Jurassic Park.*
"""

[taxonomies]
tag = "tags"
category = "categories"

[params]
ShowToc = true
ShowWordCount = true
label.iconWidth = 30
defaultTheme = "auto"
label.iconHeight = 30
ShowReadingTime = true
label.icon = "logo.svg"
ShowShareButtons = false
images = ["/logo-512x512"]
displayFullLangName = true
ShowCodeCopyButtons = true
assets.theme_color = "#0f94d2"
assets.msapplication_TileColor = "#2b5797"

[[customScripts]]

[[params.customStyles]]
file = "/css/offline.css"
integrity = "sha512-+R/cu1jJ/RrydyUhKhXI1QczU3TRLLLHAQyYHi1vXFAEF8lK4MxJiWgjIckiCegJ80aIB6icc6lSoLn1YY/OSA=="

[[params.notificationsScripts]]
file = "/js/notifications/dictionary.js"
integrity = "sha512-tOZZsofKwRGHAcQVGMed077Q0y4hnPvTv0Nw8L9VYWKlQgWcQZznMXZTTNID39Q0+Dumx+kHl7PlP7K+cGn6nQ=="

[[params.notificationsScripts]]
file = "/js/notifications/i18n.js"
integrity = "sha512-eNnuCLQ8noOgoy620xyZxApQlMLSJZze6Qe/h/uKQIynxfvYfmL29FimkcLho1i7AGeG+tkh0WM5pnBcIn82Hg=="

[[params.notificationsScripts]]
file = "/js/notifications/main.js"
integrity = "sha512-SAID9CBhh48e0EabUHvgvRrh2FiCmBh5Xb+fX2sv5P9IhYvRC73fYNHWg6usTYMyEOvJ6uEuP9y7nTQIgr0f7w=="

[[params.socialIcons]]
name = "github"
url = "https://github.com/sponsors/Airscripts"

[[params.socialIcons]]
name = "KoFi"
url = "https://ko-fi.com/airscript"

[[params.socialIcons]]
name = "RSS"
url = "https://blog.airscript.it/index.xml"

[params.editPost]
appendFilePath = false
Text = "Suggest Changes"
URL = "https://github.com/Airscripts/blog.airscript.it/tree/main/content"

[outputs]
home = [ "HTML", "RSS", "JSON" ]
