#!/bin/bash
readonly INSTALL_NPM="npm installed successfully."
readonly INSTALL_GIT="Git installed successfully."
readonly INSTALL_GPP="gpp installed successfully."
readonly INSTALL_BATS="Bats installed successfully."
readonly INSTALL_HUGO="Hugo installed successfully."
readonly INSTALL_MAKE="Make installed successfully."
readonly INSTALL_CURL="curl installed successfully."
readonly INSTALL_BASH="Bash installed successfully."
readonly INSTALL_PYTHON3="python3 installed successfully."
readonly INSTALL_DOCKER_CLI="Docker CLI installed successfully."
readonly INSTALL_NETLIFY_CLI="Netlify CLI installed successfully."
readonly INSTALL_CIRCLECI_CLI="CircleCI CLI installed successfully."
readonly INSTALL_DEVCONTAINER_CLI="devcontainer CLI installed successfully."

readonly SKIP_INSTALL_GIT="Git installation has been skipped."
readonly ADD_GIT_SUBMODULE_SKIPPED="Git submodule update skipped."
readonly ADD_GIT_SUBMODULE_EXECUTED="Git submodule update executed."
