#!/bin/bash
readonly INSTALL_NPM="npm installed successfully."
readonly INSTALL_GIT="Git installed successfully."
readonly INSTALL_HUGO="Hugo installed successfully."
readonly INSTALL_MAKE="Make installed successfully."
readonly INSTALL_BASH="Bash installed successfully."
readonly SKIP_INSTALL_GIT="Git installation has been skipped."
readonly INSTALL_DOCKER_CLI="Docker CLI installed successfully."
readonly INSTALL_NETLIFY_CLI="Netlify CLI installed successfully."
readonly ADD_GIT_SUBMODULE_SKIPPED="Git submodule update skipped."
readonly ADD_GIT_SUBMODULE_EXECUTED="Git submodule update executed."
