version: 2.1

executors:
  build-environment:
    docker:
      - image: alpine:3.16

  deploy-environment:
    docker:
      - image: node:18.7.0-alpine3.16
    
  publish-environment:
    docker:
      - image: docker:20.10.17-cli-alpine3.16

jobs:
  verify-build-environment:
    executor: build-environment
      
    steps:
      - run:
          name: "Verify apk"
          command: "apk"
  
  verify-deploy-environment:
    executor: deploy-environment

    steps:
      - run:
          name: "Verify apk"
          command: "apk"
      
      - run: 
          name: "Verify Node.js"
          command: "node -v"

      - run: 
          name: "Verify npm"
          command: "npm -v"
        
  verify-publish-environment:
    executor: publish-environment

    steps:
      - run:
          name: "Verify Docker"
          command: "docker -v"

  build:
    executor: build-environment
      
    steps:
      - checkout

      - run:
          name: "Update Alpine Repositories"
          command: "apk update"

      - run:
          name: "Install Git"
          command: "apk add git"
        
      - run:
          name: "Update Git Submodules"
          command: "git submodule update --init --recursive"

      - run:
          name: "Install Hugo"
          command: "apk add hugo"
      
      - run:
          name: "Building Site"
          command: "hugo --gc --minify"
        
      - persist_to_workspace:
          root: .

          paths:
            - ./public
    
  deploy:
    executor: deploy-environment

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: "Update Alpine Repositories"
          command: "apk update"

      - run:
          name: "Update npm"
          command: "npm install -g npm"
      
      - run:
          name: "Install Netlify CLI"
          command: "npm install -g netlify-cli"
      
      - run:
          name: "Deploy To Netlify"
          command: "netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=public"

  publish:
    executor: publish-environment

    steps:
      - checkout

      - run:
          name: "Login Into Docker Hub"
          command: "docker login --username $DOCKER_USERNAME --password $DOCKER_ACCESS_TOKEN"

      - run:
          name: "Build Docker Image"
          command: "docker build -f .docker/blog.Dockerfile -t airscript/blog:$CIRCLE_TAG ."  

      - run:
          name: "Publish To Docker Hub"
          command: "docker push airscript/blog:$CIRCLE_TAG"

workflows:
  verify:
    jobs:
      - verify-build-environment
      - verify-deploy-environment
      - verify-publish-environment

  build:
    jobs:
      - build

  deploy:
    jobs:
      - build
      
      - deploy:
          requires:
            - build

          filters:
              branches:
                only:
                  - main
  publish:
    jobs:
      - publish:
          filters: 
            tags:
              only: 
                - /.*/

            branches:
              ignore: /.*/