version: 2.1

jobs:
  verify:
    docker:
      - image: node:18.7.0-alpine3.16
      
    steps:
      - checkout

      - run:
          name: "Verify Job"
          command: "echo Verify job is working!"

  build:
    docker:
      - image: node:18.7.0-alpine3.16
      
    steps:
      - checkout

      - run:
          name: "Update Alpine Repositories"
          command: "apk update"

      - run:
          name: "Install Hugo"
          command: "apk add hugo"
      
      - run:
          name: "Building Site"
          command: "hugo --gc --minify"
    
  deploy:
    docker:
      - image: node:18.7.0-alpine3.16

    steps:
      - checkout

      - run:
          name: "Update Alpine Repositories"
          command: "apk update"

      - run:
          name: "Install Git"
          command: "apk add git"
        
      - run:
          name: "Update Git Submodules"
          command: "git submodule update --init --recursive"

      - run:
          name: "Install Hugo"
          command: "apk add hugo"

      - run:
          name: "Building Site"
          command: "HUGO_ENV=production hugo --gc --minify"

      - run:
          name: "Update npm"
          command: "npm install -g npm"
      
      - run:
          name: "Install Netlify CLI"
          command: "npm install -g netlify-cli"
      
      - run:
          name: "Deploy To Netlify"
          command: "netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=public"
    
workflows:
  verify:
    jobs:
      - verify

  build:
    jobs:
      - build

  deploy:
    jobs:
      - deploy:
          filters:
              branches:
                only:
                  - main
