version: 2.1

executors:
  build-environment:
    docker:
      - image: alpine:3.16

  deploy-environment:
    docker:
      - image: node:18.7.0-alpine3.16
    
  publish-environment:
    docker:
      - image: alpine:3.16

jobs:
  verify-build-environment:
    executor: build-environment
      
    steps:
      - checkout

      - run:
          name: Verify Environment
          command: sh ./scripts/ci/verify.sh build
  
  verify-deploy-environment:
    executor: deploy-environment

    steps:
      - checkout

      - run:
          name: Verify Environment
          command: sh ./scripts/ci/verify.sh deploy

  verify-publish-environment:
    executor: publish-environment

    steps:
      - checkout

      - run:
          name: Verify Environment
          command: sh ./scripts/ci/verify.sh publish

  build:
    executor: build-environment
      
    steps:
      - checkout

      - run:
          name: Install Packages

          command: |
            apk update
            sh ./scripts/install/make.sh
            make install-git env=$BLOG_BUILD_ENV
            make install-hugo
        
      - run:
          name: Add Git Submodules
          command: make git-submodules env=$BLOG_BUILD_ENV
      
      - run:
          name: Building Site
          command: make build-ci

      - when:
          condition: 
            equal: [ main, << pipeline.git.branch >>]

          steps:
            - persist_to_workspace:
                root: .

                paths:
                  - ./public

  deploy:
    executor: deploy-environment

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: Install Packages

          command: |
            apk update
            sh ./scripts/install/make.sh
            make install-npm
            make install-netlify-cli
      
      - run:
          name: Deploy To Netlify
          command: make deploy-ci id=$NETLIFY_SITE_ID token=$NETLIFY_ACCESS_TOKEN

  publish:
    executor: publish-environment

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14

      - run:
          name: Install Packages
          command: |
            apk update
            sh ./scripts/install/make.sh
            make install-docker-cli

      - run:
          name: Publish To Docker Hub
          command: make publish-ci tag=$CIRCLE_TAG username=$DOCKER_USERNAME token=$DOCKER_ACCESS_TOKEN

workflows:
  verify:
    jobs:
      - verify-build-environment
      - verify-deploy-environment
      - verify-publish-environment

  build:
    jobs:
      - build

  deploy:
    jobs:
      - build
      
      - deploy:
          requires:
            - build

          filters:
              branches:
                only:
                  - main
  publish:
    jobs:
      - publish:
          filters: 
            tags:
              only: 
                - /.*/

            branches:
              ignore: /.*/
