version: 2.1

setup: true

orbs: 
  path-filtering: circleci/path-filtering@0.1.3

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          name: workflows
          base-revision: main
          config-path: .circleci/workflows.yml

          mapping: |
            tests/.* test true
