version: 2.1

executors:
  build-environment:
    docker:
      - image: alpine:3.16

  deploy-environment:
    docker:
      - image: node:18.7.0-alpine3.16
    
  publish-environment:
    docker:
      - image: alpine:3.16

jobs:
  verify-build-environment:
    executor: build-environment
      
    steps:
      - checkout

      - run:
          name: Verify Environment
          command: |
            apk update
            sh scripts/install/bash.sh $BLOG_BUILD_ENV
            bash scripts/ci/verify.sh build
  
  verify-deploy-environment:
    executor: deploy-environment

    steps:
      - checkout

      - run:
          name: Verify Environment
          command: |
            apk update
            sh scripts/install/bash.sh $BLOG_BUILD_ENV
            bash scripts/ci/verify.sh deploy

  verify-publish-environment:
    executor: publish-environment

    steps:
      - checkout

      - run:
          name: Verify Environment
          command: |
            apk update
            sh scripts/install/bash.sh $BLOG_BUILD_ENV
            bash scripts/ci/verify.sh publish

workflows:
  verify:
    jobs:
      - verify-build-environment

      - verify-deploy-environment:
          filters:
            branches:
              only:
                - main

      - verify-publish-environment:
          filters:
            branches:
              only:
                - main